services:
  moveit2:
    build:
      context: ..
      dockerfile: basestation/Dockerfile
    environment:
      ROS_DOMAIN_ID: '${ROS_DOMAIN_ID:-0}'
      ROS_LOCALHOST_ONLY: '0'
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      ROS_DISCOVERY_SERVER: '${ROVER_DISCOVERY_SERVER:-rover.local:11811}'
