services:
  media-gateway:
    extends:
      file: docker-compose.yml
      service: media-gateway
    environment:
      MTX_WEBRTCADDITIONALHOSTS: 'localhost,127.0.0.1'
      MTX_WEBRTCALLOWORIGINS: 'http://localhost:4200,http://127.0.0.1:4200'

  moveit2:
    build:
      context: ..
      dockerfile: basestation/Dockerfile
    environment:
      ROS_DISCOVERY_SERVER: 127.0.0.1:11811
      ROS_DOMAIN_ID: '${ROS_DOMAIN_ID:-0}'
      ROS_LOCALHOST_ONLY: '0'
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
