import { EcamAlertCode, EcamAlertDefinition } from './ecam-alert.types';

/**
 * The single source of truth for ECAM message wording, source, and severity.
 * Features raise stable codes; they do not choose colours or user-facing text.
 */
export const ECAM_MESSAGE_CATALOG: Readonly<Record<EcamAlertCode, EcamAlertDefinition>> = {
  ARM_CAN_FAULT: {
    code: 'ARM_CAN_FAULT',
    source: 'ARM',
    severity: 'fault',
    text: 'ARM CAN FAULT',
  },
  ARM_JOINT_FAULT: {
    code: 'ARM_JOINT_FAULT',
    source: 'ARM',
    severity: 'fault',
    text: 'ARM JOINT FAULT',
  },
  ARM_JOINT_LIMIT: {
    code: 'ARM_JOINT_LIMIT',
    source: 'ARM',
    severity: 'warning',
    text: 'ARM JOINT LIMIT',
  },
  ARM_OVERTEMPERATURE: {
    code: 'ARM_OVERTEMPERATURE',
    source: 'ARM',
    severity: 'warning',
    text: 'ARM OVERTEMPERATURE',
  },
  ARM_PLANNER_FAULT: {
    code: 'ARM_PLANNER_FAULT',
    source: 'ARM',
    severity: 'fault',
    text: 'ARM PLANNER FAULT',
  },
  ARM_PLANNER_TIMEOUT: {
    code: 'ARM_PLANNER_TIMEOUT',
    source: 'ARM',
    severity: 'warning',
    text: 'ARM PLANNER TIMEOUT',
  },
  ARM_POSITION_SENSOR_INVALID: {
    code: 'ARM_POSITION_SENSOR_INVALID',
    source: 'ARM',
    severity: 'fault',
    text: 'ARM POSITION SENSOR INVALID',
  },
  ARM_PROTECTION_UNAVAILABLE: {
    code: 'ARM_PROTECTION_UNAVAILABLE',
    source: 'ARM',
    severity: 'warning',
    text: 'ARM PROTECTION UNAVAILABLE',
  },
  ARM_TELEMETRY_UNAVAILABLE: {
    code: 'ARM_TELEMETRY_UNAVAILABLE',
    source: 'ARM',
    severity: 'warning',
    text: 'ARM TELEMETRY UNAVAILABLE',
  },
  CAMERA_ARM_LOST: {
    code: 'CAMERA_ARM_LOST',
    source: 'CAMERA',
    severity: 'attention',
    text: 'ARM CAMERA LOST',
  },
  CAMERA_ARM_RECONNECT_FAILED: {
    code: 'CAMERA_ARM_RECONNECT_FAILED',
    source: 'CAMERA',
    severity: 'warning',
    text: 'ARM CAMERA RECONNECT FAILED',
  },
  CAMERA_ARM_STREAM_LOST: {
    code: 'CAMERA_ARM_STREAM_LOST',
    source: 'CAMERA',
    severity: 'warning',
    text: 'ARM CAMERA STREAM LOST',
  },
  CAMERA_FRONT_LOST: {
    code: 'CAMERA_FRONT_LOST',
    source: 'CAMERA',
    severity: 'attention',
    text: 'FRONT CAMERA LOST',
  },
  CAMERA_FRONT_RECONNECT_FAILED: {
    code: 'CAMERA_FRONT_RECONNECT_FAILED',
    source: 'CAMERA',
    severity: 'warning',
    text: 'FRONT CAMERA RECONNECT FAILED',
  },
  CAMERA_FRONT_STREAM_LOST: {
    code: 'CAMERA_FRONT_STREAM_LOST',
    source: 'CAMERA',
    severity: 'warning',
    text: 'FRONT CAMERA STREAM LOST',
  },
  CAMERA_GIMBAL_LOST: {
    code: 'CAMERA_GIMBAL_LOST',
    source: 'CAMERA',
    severity: 'attention',
    text: 'GIMBAL CAMERA LOST',
  },
  CAMERA_GIMBAL_RECONNECT_FAILED: {
    code: 'CAMERA_GIMBAL_RECONNECT_FAILED',
    source: 'CAMERA',
    severity: 'warning',
    text: 'GIMBAL CAMERA RECONNECT FAILED',
  },
  CAMERA_GIMBAL_STREAM_LOST: {
    code: 'CAMERA_GIMBAL_STREAM_LOST',
    source: 'CAMERA',
    severity: 'warning',
    text: 'GIMBAL CAMERA STREAM LOST',
  },
  CAMERA_LATENCY_HIGH: {
    code: 'CAMERA_LATENCY_HIGH',
    source: 'CAMERA',
    severity: 'warning',
    text: 'CAMERA LATENCY HIGH',
  },
  GIMBAL_CONTROL_FAULT: {
    code: 'GIMBAL_CONTROL_FAULT',
    source: 'CAMERA',
    severity: 'fault',
    text: 'GIMBAL CONTROL FAULT',
  },
  GIMBAL_POSITION_UNKNOWN: {
    code: 'GIMBAL_POSITION_UNKNOWN',
    source: 'CAMERA',
    severity: 'warning',
    text: 'GIMBAL POSITION UNKNOWN',
  },
  GIMBAL_PRIORITY_UNKNOWN: {
    code: 'GIMBAL_PRIORITY_UNKNOWN',
    source: 'CAMERA',
    severity: 'warning',
    text: 'GIMBAL PRIORITY UNKNOWN',
  },
  CONFIG_ANTENNA_NOT_DEPLOYED: {
    code: 'CONFIG_ANTENNA_NOT_DEPLOYED',
    source: 'CONFIG',
    severity: 'attention',
    text: 'CONFIG ANTENNA NOT DEPLOYED',
  },
  CONFIG_ARM_NOT_STOWED: {
    code: 'CONFIG_ARM_NOT_STOWED',
    source: 'CONFIG',
    severity: 'attention',
    text: 'CONFIG ARM NOT STOWED',
  },
  CONFIG_ARM_NOT_READY: {
    code: 'CONFIG_ARM_NOT_READY',
    source: 'CONFIG',
    severity: 'warning',
    text: 'CONFIG ARM NOT READY',
  },
  CONFIG_CONTROLLER_NOT_CONNECTED: {
    code: 'CONFIG_CONTROLLER_NOT_CONNECTED',
    source: 'CONFIG',
    severity: 'warning',
    text: 'CONFIG CONTROLLER NOT CONNECTED',
  },
  CONFIG_DRIVE_NOT_READY: {
    code: 'CONFIG_DRIVE_NOT_READY',
    source: 'CONFIG',
    severity: 'warning',
    text: 'CONFIG DRIVE NOT READY',
  },
  CONFIG_ESTOP_ACTIVE: {
    code: 'CONFIG_ESTOP_ACTIVE',
    source: 'CONFIG',
    severity: 'fault',
    text: 'CONFIG E-STOP ACTIVE',
  },
  CONFIG_ESTOP_STATUS_UNAVAILABLE: {
    code: 'CONFIG_ESTOP_STATUS_UNAVAILABLE',
    source: 'CONFIG',
    severity: 'fault',
    text: 'CONFIG E-STOP STATUS UNAVAILABLE',
  },
  CONFIG_LINK_NOT_READY: {
    code: 'CONFIG_LINK_NOT_READY',
    source: 'CONFIG',
    severity: 'warning',
    text: 'CONFIG LINK NOT READY',
  },
  CONFIG_LAW_DIRECT: {
    code: 'CONFIG_LAW_DIRECT',
    procedure: {
      steps: [
        { id: 'confirm-authority', instruction: 'CONFIRM DIRECT AUTHORISED' },
        { id: 'confirm-clearance', instruction: 'CONFIRM ROVER STATIONARY AND ARM AREA CLEAR' },
        { id: 'operate-visually', instruction: 'OPERATE UNDER DIRECT VISUAL SUPERVISION' },
        { id: 'restore-normal', instruction: 'RESTORE LAW NORMAL' },
        { id: 'do-not-depart', instruction: 'DO NOT DEPART IF UNABLE' },
        { id: 'mockup-placeholder', instruction: 'MOCK-UP — FINAL STEPS PENDING LEAD REVIEW' },
      ],
    },
    source: 'CONFIG',
    severity: 'warning',
    text: 'CONFIG LAW DIRECT',
  },
  DRIVE_CONTROLLER_OFFLINE: {
    code: 'DRIVE_CONTROLLER_OFFLINE',
    procedure: {
      steps: [
        { id: 'check-link', instruction: 'CONFIRM LINK GOOD' },
        { id: 'retry-controller', instruction: 'RETRY DRIVE-CONTROLLER CONNECTION' },
        { id: 'confirm-heartbeat', instruction: 'CONFIRM DRIVE-CONTROLLER HEARTBEAT' },
        { id: 'stop-driving', instruction: 'DO NOT DRIVE IF UNRESOLVED' },
        { id: 'mockup-placeholder', instruction: 'MOCK-UP — FINAL STEPS PENDING LEAD REVIEW' },
      ],
    },
    source: 'DRIVE',
    severity: 'fault',
    text: 'DRIVE CONTROLLER OFFLINE',
  },
  DRIVE_DRIVETRAIN_FAULT: {
    code: 'DRIVE_DRIVETRAIN_FAULT',
    source: 'DRIVE',
    severity: 'fault',
    text: 'DRIVETRAIN FAULT',
  },
  DRIVE_FL_OVERCURRENT: {
    code: 'DRIVE_FL_OVERCURRENT',
    source: 'DRIVE',
    severity: 'fault',
    text: 'FL MOTOR OVERCURRENT',
  },
  DRIVE_FR_OVERCURRENT: {
    code: 'DRIVE_FR_OVERCURRENT',
    source: 'DRIVE',
    severity: 'fault',
    text: 'FR MOTOR OVERCURRENT',
  },
  DRIVE_RL_OVERCURRENT: {
    code: 'DRIVE_RL_OVERCURRENT',
    source: 'DRIVE',
    severity: 'fault',
    text: 'RL MOTOR OVERCURRENT',
  },
  DRIVE_RR_OVERCURRENT: {
    code: 'DRIVE_RR_OVERCURRENT',
    source: 'DRIVE',
    severity: 'fault',
    text: 'RR MOTOR OVERCURRENT',
  },
  DRIVE_FL_OVERTEMPERATURE: {
    code: 'DRIVE_FL_OVERTEMPERATURE',
    source: 'DRIVE',
    severity: 'warning',
    text: 'FL MOTOR OVERTEMPERATURE',
  },
  DRIVE_FR_OVERTEMPERATURE: {
    code: 'DRIVE_FR_OVERTEMPERATURE',
    source: 'DRIVE',
    severity: 'warning',
    text: 'FR MOTOR OVERTEMPERATURE',
  },
  DRIVE_FL_MOTION_MISMATCH: {
    code: 'DRIVE_FL_MOTION_MISMATCH',
    source: 'DRIVE',
    severity: 'warning',
    text: 'FL MOTION MISMATCH',
  },
  DRIVE_FR_MOTION_MISMATCH: {
    code: 'DRIVE_FR_MOTION_MISMATCH',
    source: 'DRIVE',
    severity: 'warning',
    text: 'FR MOTION MISMATCH',
  },
  DRIVE_FL_MOTOR_FAULT: {
    code: 'DRIVE_FL_MOTOR_FAULT',
    source: 'DRIVE',
    severity: 'fault',
    text: 'FL MOTOR FAULT',
  },
  DRIVE_FR_MOTOR_FAULT: {
    code: 'DRIVE_FR_MOTOR_FAULT',
    source: 'DRIVE',
    severity: 'fault',
    text: 'FR MOTOR FAULT',
  },
  DRIVE_RL_OVERTEMPERATURE: {
    code: 'DRIVE_RL_OVERTEMPERATURE',
    source: 'DRIVE',
    severity: 'warning',
    text: 'RL MOTOR OVERTEMPERATURE',
  },
  DRIVE_RR_OVERTEMPERATURE: {
    code: 'DRIVE_RR_OVERTEMPERATURE',
    source: 'DRIVE',
    severity: 'warning',
    text: 'RR MOTOR OVERTEMPERATURE',
  },
  DRIVE_RL_MOTION_MISMATCH: {
    code: 'DRIVE_RL_MOTION_MISMATCH',
    source: 'DRIVE',
    severity: 'warning',
    text: 'RL MOTION MISMATCH',
  },
  DRIVE_RL_MOTOR_FAULT: {
    code: 'DRIVE_RL_MOTOR_FAULT',
    source: 'DRIVE',
    severity: 'fault',
    text: 'RL MOTOR FAULT',
  },
  DRIVE_RR_MOTION_MISMATCH: {
    code: 'DRIVE_RR_MOTION_MISMATCH',
    source: 'DRIVE',
    severity: 'warning',
    text: 'RR MOTION MISMATCH',
  },
  DRIVE_RR_MOTOR_FAULT: {
    code: 'DRIVE_RR_MOTOR_FAULT',
    source: 'DRIVE',
    severity: 'fault',
    text: 'RR MOTOR FAULT',
  },
  DRIVE_RS485_FAULT: {
    code: 'DRIVE_RS485_FAULT',
    source: 'DRIVE',
    severity: 'fault',
    text: 'DRIVE RS485 FAULT',
  },
  DRIVE_TELEMETRY_UNAVAILABLE: {
    code: 'DRIVE_TELEMETRY_UNAVAILABLE',
    source: 'DRIVE',
    severity: 'warning',
    text: 'DRIVE TELEMETRY UNAVAILABLE',
  },
  LINK_DEGRADED: {
    code: 'LINK_DEGRADED',
    source: 'LINK',
    severity: 'warning',
    text: 'LINK DEGRADED',
  },
  LINK_CONTROLLER_DISCONNECTED: {
    code: 'LINK_CONTROLLER_DISCONNECTED',
    source: 'LINK',
    severity: 'fault',
    text: 'CONTROLLER DISCONNECTED',
  },
  LINK_LATENCY_HIGH: {
    code: 'LINK_LATENCY_HIGH',
    source: 'LINK',
    severity: 'warning',
    text: 'LINK LATENCY HIGH',
  },
  LINK_LOST: {
    code: 'LINK_LOST',
    source: 'LINK',
    severity: 'fault',
    text: 'LINK LOST',
  },
  LINK_PACKET_LOSS_HIGH: {
    code: 'LINK_PACKET_LOSS_HIGH',
    source: 'LINK',
    severity: 'warning',
    text: 'LINK PACKET LOSS HIGH',
  },
  LINK_ROS_UNAVAILABLE: {
    code: 'LINK_ROS_UNAVAILABLE',
    source: 'LINK',
    severity: 'fault',
    text: 'LINK ROS UNAVAILABLE',
  },
  POWER_BATTERY_LOW: {
    code: 'POWER_BATTERY_LOW',
    source: 'POWER',
    severity: 'warning',
    text: 'BATTERY LOW',
  },
  POWER_BATTERY_UNAVAILABLE: {
    code: 'POWER_BATTERY_UNAVAILABLE',
    source: 'POWER',
    severity: 'fault',
    text: 'BATTERY DATA UNAVAILABLE',
  },
  POWER_RAIL_FAULT: {
    code: 'POWER_RAIL_FAULT',
    source: 'POWER',
    severity: 'fault',
    text: 'POWER RAIL FAULT',
  },
  POWER_TOTAL_POWER_UNAVAILABLE: {
    code: 'POWER_TOTAL_POWER_UNAVAILABLE',
    source: 'POWER',
    severity: 'warning',
    text: 'TOTAL POWER UNAVAILABLE',
  },
  SYSTEM_CPU_HIGH: {
    code: 'SYSTEM_CPU_HIGH',
    source: 'SYSTEM',
    severity: 'warning',
    text: 'CPU LOAD HIGH',
  },
  SYSTEM_CRITICAL_FAULT: {
    code: 'SYSTEM_CRITICAL_FAULT',
    source: 'SYSTEM',
    severity: 'fault',
    text: 'SYSTEM CRITICAL FAULT',
  },
  SYSTEM_DIAGNOSTICS_UNAVAILABLE: {
    code: 'SYSTEM_DIAGNOSTICS_UNAVAILABLE',
    source: 'SYSTEM',
    severity: 'warning',
    text: 'SYSTEM DIAGNOSTICS UNAVAILABLE',
  },
  SYSTEM_ESTOP_ACTIVE: {
    code: 'SYSTEM_ESTOP_ACTIVE',
    source: 'SYSTEM',
    severity: 'fault',
    text: 'E-STOP ACTIVE',
  },
  SYSTEM_LED_FAULT: {
    code: 'SYSTEM_LED_FAULT',
    source: 'SYSTEM',
    severity: 'warning',
    text: 'LED FAULT',
  },
  SYSTEM_MEMORY_HIGH: {
    code: 'SYSTEM_MEMORY_HIGH',
    source: 'SYSTEM',
    severity: 'warning',
    text: 'MEMORY USE HIGH',
  },
  SYSTEM_ROS_NODE_FAULT: {
    code: 'SYSTEM_ROS_NODE_FAULT',
    source: 'SYSTEM',
    severity: 'fault',
    text: 'ROS NODE FAULT',
  },
  SYSTEM_ROS_SERVICE_UNAVAILABLE: {
    code: 'SYSTEM_ROS_SERVICE_UNAVAILABLE',
    source: 'SYSTEM',
    severity: 'fault',
    text: 'ROS SERVICE UNAVAILABLE',
  },
  SYSTEM_STORAGE_LOW: {
    code: 'SYSTEM_STORAGE_LOW',
    source: 'SYSTEM',
    severity: 'warning',
    text: 'STORAGE LOW',
  },
  SYSTEM_TELEMETRY_STALE: {
    code: 'SYSTEM_TELEMETRY_STALE',
    source: 'SYSTEM',
    severity: 'warning',
    text: 'SYSTEM TELEMETRY STALE',
  },
  SYSTEM_TEMPERATURE_HIGH: {
    code: 'SYSTEM_TEMPERATURE_HIGH',
    source: 'SYSTEM',
    severity: 'warning',
    text: 'SYSTEM TEMPERATURE HIGH',
  },
  SYSTEM_WATCHDOG_FAULT: {
    code: 'SYSTEM_WATCHDOG_FAULT',
    source: 'SYSTEM',
    severity: 'fault',
    text: 'SYSTEM WATCHDOG FAULT',
  },
};
